name: Connecting to ec2 and run commands
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: ssh -i "Newkey.pem" ec2-user@ec2-3-87-67-222.compute-1.amazonaws.com
      
     
